baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My Fancy Blog or Whatever'
theme = "beautifulhugo"

[taxonomies]
  tag = 'tags'

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "posts"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
